# Generated by Django 5.2.7 on 2025-11-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('description', models.TextField()),
                ('poster', models.URLField()),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
        ),
    ]
