# Generated by Django 5.2.8 on 2025-11-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.CharField(default='movie', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.URLField(null=True),
        ),
    ]
