# Generated by Django 5.2.8 on 2025-11-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_site', '0003_favorite_genre_media_profile_usermedia_delete_movie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedia',
            name='status',
            field=models.CharField(choices=[('Watched', 'Watched'), ('Watchlist', 'To Watch')], default='Watchlist', max_length=20),
        ),
    ]
