# Generated by Django 5.2.8 on 2025-11-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_site', '0004_usermedia_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'permissions': [('edit_media', 'can edit media')]},
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pic/profile_pics'),
        ),
    ]
