# Generated by Django 5.2.8 on 2025-11-22 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_site', '0005_alter_media_options_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermedia',
            options={'ordering': ['-added_at'], 'permissions': [('view_user_media', 'can view user media'), ('edit_user_media', 'can edit user media'), ('delete_user_media', 'can delete user media')]},
        ),
    ]
