# Generated by Django 5.2.8 on 2026-02-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_site', '0008_question_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizattempt',
            name='total_questions',
            field=models.IntegerField(default=10),
        ),
    ]
